spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev    #开发环境
  application:
    name: microservicecloud-config-tusvn-test
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-tusvn-test
# 保存为UTF-8格式